spring.application.name=patient-web-service

# =====================================
# DATABASE - PostgreSQL
# Có thể thay đổi bằng biến môi trường DB_URL, DB_USERNAME, DB_PASSWORD.
# =====================================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/medical_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# =====================================
# BÀI 2 - LOG LEVEL
# =====================================
# Log toàn bộ ứng dụng từ INFO trở lên.
logging.level.root=INFO

# Hiển thị SQL do Hibernate gửi xuống database.
logging.level.org.hibernate.SQL=DEBUG

# Hiển thị TRACE trong tầng service.
logging.level.com.medical.service=TRACE

# Căn chỉnh SQL để dễ đọc trong Console và file log.
spring.jpa.properties.hibernate.format_sql=true

# Có thể bỏ comment để xem cả giá trị được bind vào dấu ? trong SQL.
# logging.level.org.hibernate.orm.jdbc.bind=TRACE

# =====================================
# BÀI 3 - LOGGING TO FILE + ROTATION
# =====================================
logging.file.name=logs/patient_web_service.log
logging.logback.rollingpolicy.max-file-size=2MB
logging.logback.rollingpolicy.file-name-pattern=${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
logging.logback.rollingpolicy.max-history=7
